# main.py
import tkinter as tk
from modules.gui.app import ModernUwezoTradingApp
import sys
import os

def resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller."""
    if getattr(sys, 'frozen', False):
        base_path = sys._MEIPASS
    else:
        base_path = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(base_path, relative_path)

def main():
    root = tk.Tk()
    app = ModernUwezoTradingApp(root)
    root.mainloop()

def create_sample_config():
    """Create sample configuration file"""
    import json
    sample_config = {
        "symbol": None,
        "magic_number": 202401,
        "slippage": 20,
        "reversal_mode": False,
        "auto_trading": False,
        "idle_timeout_minutes": 10,
        "database_file": "trading_users.db",
        "profile_photo_folder": "profile_photos",
        "min_trades_per_signal": 5,
        "max_trades_per_session": 5,
        "max_concurrent_positions": 5,
        "aggressive_mode_positions": 5,
        "position_sizing_method": "fixed",
        "risk_per_trade": 0.02,
        "fixed_lot_size": 0.01,
        "max_position_size": 1.0,
        "min_position_size": 0.01,
        "max_daily_loss_percent": 20.0,
        "max_drawdown": 20.0,
        "max_consecutive_losses": 5,
        "stop_loss_pips": 50.0,
        "take_profit_pips": 100.0,
        "enable_stop_loss": True,
        "enable_take_profit": True,
        "close_opposite_on_signal_change": False,
        "trading_start_hour": 0,
        "trading_end_hour": 23,
        "aggressive_trade_interval": 30,
        "normal_trade_interval": 60,
        "aggressive_trades_per_minute": 2,
        "ema_fast_period": 9,
        "ema_slow_period": 21,
        "rsi_overbought": 70.0,
        "rsi_oversold": 30.0,
        "cci_overbought": 100.0,
        "cci_oversold": -100.0,
        "williams_overbought": -20.0,
        "williams_oversold": -80.0,
        "require_all_timeframes_aligned": False,
        "timeframe_weights": {"D1": 1.0, "H4": 0.8, "H1": 0.6, "M15": 0.4, "M5": 0.2},
        "log_level": "INFO",
        "log_file": "trading_system.log",
        "enable_trailing_stop_loss": False,
        "lock_amount_dollars": 3.0,
        "step_amount_dollars": 4.0,
        "use_sts_signal": False,
        "normal_length": 5,
        "normal_atr_period": 14,
        "normal_momentum_threshold_base": 0.01,
        "sts_length": 3,
        "sts_atr_period": 7,
        "sts_momentum_threshold_base": 0.02,
        "use_ict_mss": True,
        "use_ict_bos": True,
        "use_ict_fvg": True,
        "use_ict_ob": True,
        "use_ict_vi": True,
        "use_ict_displacement": False,
        "use_sms_momentum_filter": True,
        "use_sms_trend_filter": True,
        "use_sms_volume_filter": True,
        "use_sms_breakout_filter": True,
        "use_sms_divergence": True,
        "require_fvg_confirmation": False,
        "require_ob_confirmation": False,
        "sms_pre_momentum_factor": 0.5,
        "rsi_period": 14,
        "cci_period": 20,
        "williams_period": 14,
        "sms_volume_long_period": 50,
        "sms_volume_short_period": 5,
        "sms_breakout_period": 5,
        "max_vi": 2,
        "max_fvg": 5,
        "max_obs": 10,
        "max_swing_points": 50,
        "fvg_type": "FVG",
        "use_body_for_ob": True,
        "min_signal_distance": 5,
        "use_sts_1min": True,
        "use_sts_5min": True,
        "sts_1min_weight": 0.5,
        "sts_5min_weight": 0.5,
        "sts_alignment_threshold": 0.2,
        "weight_5min": 0.7,
        "weight_15min": 0.3,
        "alignment_threshold": 0.3,
        "myfxbook_email": "",
        "myfxbook_password": "",
        "use_news_sentiment": False,
        "cache_enabled": True,
        "cache_ttl": 300,
        "cache_dir": "cache",
        "enable_reversal_trading": False,
        "reversal_max_trades": 5,
        "reversal_cooldown_seconds": 300,
        "reversal_trade_volume": 0.01,
        "reversal_use_dynamic_sl": True,
        "reversal_max_sl_pips": 80.0,
        "reversal_min_sl_pips": 30.0,
        "reversal_require_retest": True,
        "reversal_retest_wait_seconds": 5,
        "reversal_retest_tolerance_pips": 10.0,
        "reversal_require_confirmation_candle": True,
        "reversal_confirmation_candle_body_percent": 60.0,
        "reversal_max_price_move_pips": 0,
        "reversal_use_volatility_filter": True,
        "reversal_max_atr_percent": 2.0,
        "reversal_min_atr_percent": 0.3,
        "reversal_volatility_lookback": 14,
        "reversal_require_volume_spike": True,
        "reversal_volume_multiplier": 1.5,
        "reversal_volume_lookback": 20,
        "reversal_use_momentum_filter": True,
        "reversal_momentum_period": 5,
        "reversal_min_momentum_pips": 5.0,
        "reversal_check_support_resistance": True,
        "reversal_sr_lookback_bars": 50,
        "reversal_sr_tolerance_pips": 15.0,
        "reversal_avoid_high_impact_news": True,
        "reversal_news_buffer_minutes": 30,
        "reversal_preferred_hours_start": 8,
        "reversal_preferred_hours_end": 16,
        "reversal_avoid_london_close": True,
        "reversal_avoid_friday_afternoon": True,
        "reversal_require_higher_tf_alignment": True,
        "reversal_higher_tf": "H1",
        "reversal_trend_alignment_percent": 70.0,
        "reversal_require_pattern": True,
        "reversal_valid_patterns": ["PIN_BAR", "ENGULFING", "MORNING_STAR", "EVENING_STAR", "HAMMER", "SHOOTING_STAR", "INSIDE_BAR"],
        "reversal_use_fibonacci": True,
        "reversal_fib_levels": [0.382, 0.5, 0.618],
        "reversal_fib_tolerance_pips": 5.0,
        "reversal_use_trendline_sr": True,
        "reversal_trendline_min_strength": 2,
        "reversal_confluence_zone_width": 0.01,
        "reversal_min_confidence_score": 30.0,
    }
    with open("trading_config.json", "w") as f:
        json.dump(sample_config, f, indent=4)
    print("✅ Sample configuration created: trading_config.json")

if __name__ == "__main__":
    main()